### ISSUE TITLE
Incluir Horários das palestras

### ISSUE THREAD

**Issue by lucasbuetto** [lucasbuetto/RPTecCom.web.site#18]

**Comment by mlcalache** [comment]
@lucasbuetto 
Eu acho que está ok. Mesmo gerando a barra de rolagem horizontal no celular.
Pensei em esconder a coluna trilha quando for resolução menor, mas eu acho que eu prefiro a barra de rolagem do que esconder a trilha.
O que acha?
Se concordar, podemos fechar esse Issue.
