### ISSUE TITLE
Melhorar visualização dos horários em modo Mobile

### ISSUE THREAD

**Issue by lucasbuetto** [lucasbuetto/RPTecCom.web.site#22]

**Comment by mlcalache** [comment]
Conforme comentário que deixei na https://github.com/lucasbuetto/RPTecCom.web.site/issues/18
Eu acho que não precisamos nos preocupar com isso. Acho que está bom do jeito que está: http://swordmaster.com.br/rpteccom/2018/

**Comment by lucasbuetto** [comment]
Vou fazer somente uma melhoria que não vai impactar no lançamento
